=== FunThomas424242/rezeptbuch/old-technology/rezepte.dtd
<?thomas-michel document-status="draft" version="1.0"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |rezepte.dtd       |         -  TODO description  | -->
<!--                                                     -->
<!-- datum            : | 07.09.2008|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->

<!ELEMENT rezepte (rezept)+>
<!ATTLIST rezepte titel CDATA #IMPLIED>

<!ELEMENT rezept  ( titel, untertitel?, datum, (ungetestet | test), verwertung?
				  , produkte?, zutaten, beilagen?, zubereitung, tipps?, quelle?)>

<!ELEMENT titel (#PCDATA)>
<!ELEMENT untertitel (#PCDATA)>
<!ELEMENT datum (#PCDATA)>
<!ELEMENT ungetestet EMPTY>
<!ELEMENT test (bemerkung)+>
<!ELEMENT bemerkung (#PCDATA)>

<!ELEMENT zutaten (zutat)+>

<!ELEMENT zutat EMPTY>
<!ATTLIST zutat name CDATA #REQUIRED>
<!ATTLIST zutat menge CDATA #REQUIRED>
<!ATTLIST zutat einheit CDATA #IMPLIED>
<!ATTLIST zutat code ID	#REQUIRED>

<!ELEMENT beilagen (beilage)+>
<!ELEMENT beilage (#PCDATA)>

<!ELEMENT verwertung (rest)+>
<!ELEMENT rest EMPTY>
<!ATTLIST rest name CDATA #REQUIRED>

<!ELEMENT zubereitung (aktion)+>
<!ELEMENT aktion (#PCDATA|zutatref)*>

<!ELEMENT zutatref (#PCDATA) >
<!ATTLIST zutatref code IDREF #REQUIRED>

<!ELEMENT produkte (produkt)+>

<!ELEMENT produkt EMPTY>
<!ATTLIST produkt beschreibung CDATA #REQUIRED>
<!ATTLIST produkt ean CDATA #IMPLIED>
<!ATTLIST produkt uba CDATA #IMPLIED>
<!ATTLIST produkt preis CDATA #IMPLIED>
<!ATTLIST produkt haendler CDATA #IMPLIED>
<!ATTLIST produkt hersteller CDATA #IMPLIED>

<!ELEMENT tipps (tipp)+>
<!ELEMENT tipp (#PCDATA)>

<!ELEMENT quelle EMPTY>
<!ATTLIST quelle name CDATA #REQUIRED>
<!ATTLIST quelle modifiziert CDATA #FIXED "modifiziert">

=== FunThomas424242/rezeptbuch/old-technology/BahmiGoreng.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |BahmiGoreng.xml   |  -  TODO description         | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->
<!-- 
 standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
 :
 + Elementtypen, deren Inhalt weitere Elemente enthält, falls Leerraum (WhiteSpace)
   direkt innerhalb einer Instanz solcher Typen erscheint
 :
 -->



<rezepte>
	<rezept>
		<titel>BAHMI GORENG</titel>
		<untertitel>Gebackene Nudeln mit Fleisch</untertitel>
		<datum>24.09.2006</datum>
		<ungetestet/>
		<produkte>
			<produkt beschreibung="Sajoeran Kering (gewürztes Trockengemüse für Bahmi Goreng)" 
			         hersteller="Wan Kwai"/>
		</produkte>
		<zutaten>
			<zutat name="Wan Kwai Mie-Nudeln"
				   menge="400"
				   einheit="g"
				   code="nudeln"/> 
			<zutat name="Hühner- oder Schweinefleich"
				   menge="400" 
				   einheit="g"
				   code="fleisch"/>
			<zutat name="gekochten Schinken" 
					menge="100" 
					einheit="g"
					code="schinken"/>
			<zutat name="Porree" 
					menge="1" 
					einheit="Stange"
					code="porree"/>		
			<zutat name="Zwiebeln" 
					menge="2"
					code="zwiebeln"/>	
			<zutat name="rote Paprikatschote" 
					menge="1"
					code="paprika"/>		
			<zutat name="Sellerie" 
					menge="75" 
					einheit="g"
					code="sellerie"/>																			   
		</zutaten>
		<zubereitung>
			<aktion>
			<zutatref code="nudeln" >Mie-Nudeln</zutatref>
			nach Packungsanweisung kochen.
			</aktion>
			<aktion>
			In der Zwischenzeit das <zutatref code="fleisch">
			Fleisch</zutatref> und den 
			<zutatref code="schinken">Schinken</zutatref>
			in Würfel, <zutatref code="porree">Porree</zutatref>
			und <zutatref code="zwiebeln">Zwiebeln</zutatref> in Ringe, 
			<zutatref code="paprika">Paprika</zutatref>
			und <zutatref code="sellerie">Sellerie</zutatref>
			in Streifen scheiden.
			</aktion> 
			<aktion>
			Erbsen und Mungbohnenkeime abtropfen lassen.
			</aktion>
			<aktion>
			Öl in einer Pfanne oder im Wok erhitzen, das Fleisch kurz darin 
			anbraten, nach und nach Schinken, Zwiebeln, Porree, Sellerie und Paprika
			zugeben und mitbraten.
			</aktion>
			<aktion>
			Zum Schluß Erbsen und Mungbohnenkeime unterrühren. Das Gemüse soll
			knackig bleiben.
			</aktion>
			<aktion>
			Mit Knoflookpoeder, Djahé, Ketjap und Sambal würzen, die fertig gekochten
			Nudeln untermischen und alles noch 5 Minuten braten. Evtl. mit Salz, 
			Ketjap und Sambal abschmecken.
			</aktion>
			<aktion>
			Als Beilage gebratene Eier, gebackenen Kroepoek und Atjar Tjampoer 
			(Gemüsesalat) reichen.
			</aktion>
		</zubereitung>

		<quelle name="Wan Kwai, Ostasiatische Küche - Essen und Wohlbefinden sind eins, Seite 18"/>
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/GefüllteGemüsezwiebel.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |KartoffelbreiMitBulette.xml|  -  TODO description  | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->
<!-- 
 standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
 :
 + Elementtypen, deren Inhalt weitere Elemente enthält, falls Leerraum (WhiteSpace)
   direkt innerhalb einer Instanz solcher Typen erscheint
 :
 -->
<rezepte>
	<rezept>
		<titel>Gefüllte Gemüsezwiebel</titel>
		<datum>13.01.2008</datum>
		<test>
			<bemerkung>
			Wer kein Fleisch mag, füllt mit gequollenem Dinkel und lässt die 
			Zwiebel etwa 10 Minuten kürzer im Ofen.
			</bemerkung>
		</test>
		<zutaten>
			<zutat name="Gemüse- oder Metzgerzwiebeln"
				   menge="1"
				   einheit="kg"
				   code="zwiebel" /> 
			<zutat name="Bratwurstbrät"
				   menge="500" 
				   einheit="g"
				   code="bratwurst" />
			<zutat name="Bauchspeck" 
					menge="4" 
					einheit="dünne Scheiben"
					code="speck" />
			<zutat name="Eier" 
					menge="2"
					einheit="Stück"
					code="ei" />	
			<zutat name="Semmelbrösel" 
					menge="50"
					einheit="g"
					code="semmel" />		
			<zutat name="Salz" />	
			<zutat name="Pfeffer" />
			<zutat name="Muskat" />
			<zutat name="Kümmel" />
			<zutat name="Majoran" />
		</zutaten>
		<zubereitung>
			<aktion>Zwiebeln schälen, im Salzwasser ca. 12 Minuten kochen lassen.</aktion>		
			<aktion>Zwiebeln mit einem Schaumlöffel rausnehmen und abkühlen lassen.</aktion>
			<aktion>Einen Deckel von den Zwiebeln abschneiden und diese dann zur Hälfte aushölen.</aktion>
			<aktion>Den Inhalt vom Aushöhlen der Zwiebel vermengen mit Brät, Eiern und Semmelbröseln.</aktion>
			<aktion>Das Gemenge mit Muskat und Majoran würzen.</aktion>
			<aktion>Bei Bedarf auf mit Salz und Pfeffer würzen. Dabei aber bedenken, dass das Brät bereits
			gewürzt ist.</aktion>
			<aktion>Die entstandene Masse in die ausgehölten Zwiebeln füllen.</aktion>
			<aktion>Zwiebeln in einen Bräter setzen, mit dem Zwiebelwasser angießen, mit etwas Kümmel
			würzen und auf der mittleren Schiene bei 200 Grad 30 Minuten überbacken.</aktion>
			<aktion>Nach 20 Minuten die Speckscheiben auf die Zwiebeln legen und mitbacken.</aktion>
			<aktion>Als Beilage eignen sich Kartoffeln in verschiedenen Variationen.</aktion>
		</zubereitung>
		<!-- quelle modifiziert="modifiziert" name="der Studenten WG"/-->
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/GemüsesuppeMitSchweinefleisch.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?thomas-michel document-status="draft" version="1.3"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |NudelnMitTomatensosse.xml|  -  TODO description  | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->
<!-- 
 standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
 :
 + Elementtypen, deren Inhalt weitere Elemente enthält, falls Leerraum (WhiteSpace)
   direkt innerhalb einer Instanz solcher Typen erscheint
 :
 -->
<rezepte>
	<rezept>
		<titel>Gemüsesuppe mit Schweinefleisch</titel>
		<datum>21.10.2006</datum>
		<test>
			<bemerkung>
			Ausreichend für 2 Erwachsene und 4 Kinder.
			</bemerkung>
		</test>
		<produkte>
			<produkt beschreibung="ca. 1 kg Schulter vom Schwein"
					 ean="2260040002527"
					 preis="2,52 €"
			         hersteller="Marktkauf"/>
			<produkt beschreibung="3 mittlere Kohlrabi"/>
			<produkt beschreibung="5 Möhren"/>
			<produkt beschreibung="1 grosse Gemüsezwiebel"/>
			<produkt beschreibung="1 kleine Sellerieknolle"/>
			<produkt beschreibung="1 Stange Porree"/>
			<produkt beschreibung="1 Tüte Lorbeerblätter"/>
			<produkt beschreibung="1 Tüte Gewürznelken"/>
			<produkt beschreibung="1 Tüte Pimentkörner"/>
		</produkte>
		<zutaten>
			<zutat name="Schweinefleich (Schulter)"
				   menge="1"
				   einheit="kg"
				   code="fleisch"/> 
			<zutat name="Kohlrabi"
				   menge="3" 
				   einheit="mittelgrosse"
				   code="kohlrabi"/>
			<zutat name="Möhren" 
					menge="5" 
					code="möhren"/>		
			<zutat name="Gemüsezwiebel" 
					menge="1" 
					code="zwiebel"/>
			<zutat name="Sellerie" 
					menge="1"
					einheit="kleine Knolle"
					code="sellerie"/>	
			<zutat name="Porree" 
					menge="1" 
					einheit="Stange"
					code="porree"/>	
			<zutat name="Salz" 
					menge="nach Bedarf"
					code="salz"/>		
			<zutat name="Lorbeerblätter"
				   menge="2"
				   code="lorbeerblätter"/>															   
			<zutat name="Gewürznelken"
				   menge="2"
				   code="gewürznelken"/>															   
			<zutat name="Pimentkörner"
				   menge="4"
				   code="pimentkörner"/>															   
			<zutat name="Petersilie"
				   menge="1"
				   einheit="Bund"
				   code="petersilie"/>															   

		</zutaten>
		<beilagen>
			<beilage>
			Als Nachtisch eignet sich Obst oder Salat.
			</beilage>
		</beilagen>
		<zubereitung>
			<aktion>
			Schweinefleisch waschen und salzen.
			</aktion>
			<aktion>
			Das Fleisch in einen großen Suppentopf mit Wasser zum kochen 
			aufsetzen (E-Herd Stufe III).
			Die Wassermenge richtet sich nach der benötigten Suppenmenge. Sollte
			aber so etwa bei 2? Litern liegen. Auf jeden Fall muss das Fleich 
			vollständig bedeckt sein.
			</aktion>
			<aktion>
			<zutatref code="lorbeerblätter">Lorbeerblätter</zutatref>, 
			<zutatref code="gewürznelken">Nelken</zutatref>,
			<zutatref code="pimentkörner">Pimentkörner</zutatref> sowie
			2 Messerspitzen <zutatref code="salz">Salz</zutatref>
			in den Topf geben.
			</aktion> 
			<aktion>
			Fleisch kurz aufkochen lassen und dann 1h auf kleiner Flamme 
			weiter kochen lassen (E-Herd Stufe 1).
			</aktion>
			<aktion>
			In der Zwischenzeit das Gemüse waschen, putzen, schälen und schneiden.
			So dass Kohlrabi und Zwiebel in kleine Würfel, Möhren und Porree 
			in kleine Ringe und der Sellerie in kleinen Scheiben vorliegt. Die 
			Petersilie wird einfach klein gehächselt wie bei Kräutern üblich.
			</aktion>
			<aktion>
			Nachdem das Fleisch 1h gekocht hat, wird wieder auf grosse Flamme 
			(E-Herd Stufe II) geschalten bis sich das Fleisch vom Knochen 
			zu lösen beginnt.
			</aktion>
			<aktion>
			Fleisch aus dem Topf nehmen und den Rest auf kleiner Flamme weiter 
			kochen lassen. Sämtliches Fleisch und Fett vom Knochen lösen, 
			klein schneiden und in den Topf zurückgeben.
			Besonders große Knochen (bei Schulter sollte einer dabei sein) können
			wieder in den Topf gelegt werden um weiteres Mark auszukochen.
			</aktion>
			<aktion>
			Gleich dannach die Kohlrabi und Möhrenstücken und den Sellerie in
			den Topf geben.
			</aktion>
			<aktion>
			Nach 30 Minuten die Zwiebel und den Porree zur Suppe geben.
			</aktion>
			<aktion>
			Nach weiteren 15 Minuten die Petersilie hinzufügen.
			</aktion>
			<aktion>
			Noch ca. 15 Minuten kochen lassen bis alles weich ist und servieren.
			Die Gesamtkochzeit beträgt etwa 2h.
			</aktion>
			
		</zubereitung>
		<tipps>
			<tipp>
				Durch Zugabe von Instant Suppenpulver (Maggi) kann die Suppe 
				je nach Geschmackswunsch verändert werden.
			</tipp>
			<tipp>
				Fleisch und Fett bei Kindern besonders kleinschneiden, sonst
				wird es aussortiert.
			</tipp>
			<tipp>
				Es ist erstrebenswert das Gemüse und vor allem die Gewürze so
				kurz wie möglich im Topf zu kochen, damit noch ein paar 
				Nährstoffe und Vitamine erhalten bleiben.
			</tipp>
			<tipp>
				Bei Bedarf ist es besser das Gericht neu aufzuwärmen als es über
				länger Zeit warm zu halten.
			</tipp>
		</tipps>
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/EinfacheKekse.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |EinfacheKekse.xml|  -  TODO description  | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->
<!-- 
 standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
 :
 + Elementtypen, deren Inhalt weitere Elemente enthÃ¤lt, falls Leerraum (WhiteSpace)
   direkt innerhalb einer Instanz solcher Typen erscheint
 :
 -->
<rezepte>
	<rezept>
		<titel>Einfache Kekse</titel>
		<datum>23.12.2008</datum>
		<test>
			<bemerkung>
			Geht schnell - sind aber recht hart
			</bemerkung>
		</test>
		<produkte>
			<produkt beschreibung="1 Packung Butter"
					 haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung Zucker"
					 haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung Mehl z.B. Typ 405"
                     haendler="Marktkauf">
            </produkt>
            <produkt beschreibung="2 Eier"
                     haendler="Marktkauf">
            </produkt>
            <produkt beschreibung="2 Packungungen Vanillezucker z.B. Vanillin"
                     haendler="Marktkauf">
            </produkt>
		</produkte>
		<zutaten>
			<zutat name="Zucker"
				   menge="250"
				   einheit="g"
				   code="zucker"/> 
			<zutat name="Butter"
				   menge="250" 
				   einheit="g"
				   code="butter"/>
			<zutat name="Mehl" 
					menge="500" 
					einheit="g"
					code="mehl"/>
			<zutat name="Eier" 
                    menge="2" 
                    code="eier"/>
            <zutat name="Vanillezucker" 
                    menge="2" 
                    einheit="Pck."
                    code="vanillezucker"/>
            		
		</zutaten>
		<zubereitung>
			<aktion>Alle Zutaten vermengen und zu einem Teig verkneten.
			</aktion>		
			<aktion>Den Teig ausrollen</aktion>
			<aktion>Kekse ausstechen und auf gefettetes Blech legen</aktion>
			<aktion>10 Minuten backen</aktion>
		</zubereitung>
		<quelle name="irgendeinem Internetforum - einer von dutzenden Hinweisen zu Keksteig"/>
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/KartoffelbreiMitBulette.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |KartoffelbreiMitBulette.xml|  -  TODO description  | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->
<!-- 
 standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
 :
 + Elementtypen, deren Inhalt weitere Elemente enthält, falls Leerraum (WhiteSpace)
   direkt innerhalb einer Instanz solcher Typen erscheint
 :
 -->
<rezepte>
	<rezept>
		<titel>Kartoffelbrei mit Bulette</titel>
		<datum>09.06.2007</datum>
		<test>
			<bemerkung>
			Ein Gericht wenns mal schnell gehen soll - schmeckt ganz gut.
			</bemerkung>
		</test>
		<produkte>
			<produkt beschreibung="1 Packung Kartoffelpüree"
					 haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Glas Zigeunersosse"
					 haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung Frikadellen"
					 haendler="Marktkauf">
			</produkt>
		</produkte>
		<zutaten>
			<zutat name="Milch"
				   menge="1/2"
				   einheit="Liter"
				   code="milch"/> 
			<zutat name="Rama"
				   menge="1" 
				   einheit="EL"
				   code="butter"/>
			<zutat name="Kartoffelpüree" 
					menge="2" 
					einheit="Beutel"
					code="pueree"/>
			<zutat name="Wasser" 
					menge="1"
					einheit="Liter"
					code="wasser"/>	
			<zutat name="Salz" 
					menge="1"
					einheit="Priese"
					code="salz"/>		
			<zutat name="Buletten" 
					menge="4" 
					einheit="Stück"
					code="buletten"/>	
			<zutat name="Zigeunersosse" 
					menge="500" 
					einheit="ml"
					code="sosse"/>						
		</zutaten>
		<zubereitung>
			<aktion>Die fertige Zigeunersosse in einen kleinen Topf geben
:			</aktion>		
			<aktion>Die Buletten zur Sosse geben und den Topf auf Stufe 1 (E-Herd) 
			ca. 30 Minuten erwärmen, so dass die Buletten auch innen warm sind.</aktion>
			<aktion>Das Liter Wasser mit einer Prise Salz in einen Topf geben und zum kochen bringen.
			Beim E-Herd Stufe 3</aktion>
			<aktion>Wenn das Wasser kocht, vom Herd nehmen, Milch, Butter und 2 Beutel
			Kartoffelpüree einrühren und kurz durchrühren bis alles glatt ist</aktion>
			<aktion>servieren</aktion>
		</zubereitung>
		<!-- quelle modifiziert="modifiziert" name="der Studenten WG"/-->
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/BernburgerZwiebelklump.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |BernburgerZwiebelklump.xml|  -  TODO description  | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
	******************************************************************************
	*                                                                            *
	*   This document is a free paper; you can redistribute it and/or modify     *
	*   it under the terms of the GNU Free Documentation License as published    *
	*   by the Free Software Foundation; either version 1.2 of the License, or   *
	*   (at your option) any later version.                                      *
	*                                                                            *
	******************************************************************************
-->
<!-- 
	standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
	:
	+ Elementtypen, deren Inhalt weitere Elemente enthält, falls Leerraum (WhiteSpace)
	direkt innerhalb einer Instanz solcher Typen erscheint
	:
-->
<rezepte>
	<rezept>
		<titel>Bernburger Zwiebelklump</titel>
		<datum>07.09.2008</datum>
		<test>
			<bemerkung>
				Eines meiner Lieblingsessen aus meiner Kindheit.
			</bemerkung>
		</test>
		<zutaten>
			<zutat name="Hammelfleisch" menge="500" einheit="g"
				code="fleisch" />
			<zutat name="Zwiebeln, grbob gehackt" menge="3 große"
				code="zwiebeln" />
			<zutat name="Knoblauchzehen, fein gehackt" menge="2"
				code="knoblauch" />
			<zutat name="Salz und Pfeffer" code="salz" />
			<zutat name="Kümmel" menge="1" einheit="Teelöffel"
				code="kuemmel" />
			<zutat name="Kartoffeln" menge="750" einheit="g"
				code="kartoffeln" />
			<zutat name="Speisestärke" menge="1" einheit="Esslöffel"
				code="staerke" />
			<zutat name="Eier" menge="2" />
			<zutat name="geröstete Weißbrotwürfel" menge="2"
				einheit="Esslöffel" />
		</zutaten>
		<zubereitung>
			<aktion>
				Das Hammelfleisch in mundgerechte Stücke schneiden und
				mit den Zwiebeln, Knoblauch, Salz, Pfeffer und Kümmel in
				2 Liter Wasser zugedeckt 1 Stunde kochen.
			</aktion>
			<aktion>
				Inzwischen die Kartoffeln schälen, waschen und grob
				reiben. In ein Küchentuch wickeln und den Saft gründlich
				auspressen.
			</aktion>
			<aktion>
				Die ausgepressten Kartoffeln sofort in eine Schüssel
				geben und mit der Speisestärke, den Eiern und etwas Salz
				verrühren.
			</aktion>
			<aktion>
				Aus der Kartoffelmasse mit nassen Händen kleine Klöße
				formen. In der Mitte jeweils kleine Weißbrotwürfel
				drücken.
			</aktion>
			<aktion>
				Das Fleisch nach Ende der Garzeit aus der Brühe heben
				und warm stellen. Die Klöße in der Brühe gar ziehen
				lassen.
			</aktion>
			<aktion>
				Das Fleisch wieder in die Brühe einlegen und noch einmal
				erhitzen.
			</aktion>
		</zubereitung>
		<quelle modifiziert="modifiziert"
			name="Mairose13 im Forum http://www.chefkoch.de/forum/2,1,192997/Bernburger-Zwiebelklump.html" />

		<tipps>
			<tipp>Sehr heiß servieren.</tipp>
		</tipps>
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/Bauernfruestueck.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
	<!-- $Id$ -->
	<!-- =================================================== -->
	<!-- |Bauernfrüstück.xml|  -  TODO description  | -->
	<!--                                                     -->
	<!-- begin            : | 21.09.2006|                  | -->
	<!-- copyright        : | (C) 2006 by tmichel          | -->
	<!-- email            : |development@thomas-michel.info| -->
	<!-- =================================================== -->
	<!--
		******************************************************************************
		* * * This document is a free paper; you can redistribute it and/or
		modify * * it under the terms of the GNU Free Documentation License as
		published * * by the Free Software Foundation; either version 1.2 of
		the License, or * * (at your option) any later version. * * *
		******************************************************************************
	-->
	<!--
		standalone="no" gefordert nach XML in der Praxis S.400 (ISBN
		3-8273-1636-7) bei : + Elementtypen, deren Inhalt weitere Elemente
		enthält, falls Leerraum (WhiteSpace) direkt innerhalb einer Instanz
		solcher Typen erscheint :
	-->
<rezepte>
	<rezept>
		<titel>Bauernfrüstück</titel>
		<datum>17.08.2009</datum>
		<ungetestet />
		<zutaten>
			<zutat name="Kartoffeln" menge="750" einheit="g" code="kartoffel" />
			<zutat name="durchwachsener Speck" menge="80" einheit="g" code="speck" />
			<zutat name="Eier" menge="3" einheit="Stück" code="eier" />
			<zutat name="Milch" menge="3" einheit="EL" code="milch" />
			<zutat name="Schinkenwürfel" menge="125" einheit="g" code="schinken" />
			<zutat name="Tomaten" menge="2" einheit="Stück" code="tomaten" />
			<zutat name="Schnittlauch" code="schnittlauch" />
			<zutat name="Salz" code="salz" />
		</zutaten>
		<zubereitung>
			<aktion>Kartoffeln kochen und kalt werden lassen</aktion>
			<aktion>Kartoffeln in Scheiben schneiden, Speck klein würfeln
			</aktion>
			<aktion>Speck in der Pfanne anbraten, Kartoffeln dazugeben, salzen
				und hellbraun rösten</aktion>
			<aktion>Eier, Milch und Salz verquirlen und mit den Schinkenwürfeln
				vermischen</aktion>
			<aktion>Tomaten abziehen, klein schneiden und in die Eiermilch geben</aktion>
			<aktion>Die gesamte Milch-Mischung über die Kartoffeln geben und
				braten bis es fest wird.</aktion>
			<aktion>Abschliessend mit Schnittlauch verfeinern und servieren
			</aktion>

		</zubereitung>
		<quelle
			name="http://www.kochbar.de/rezept/anzeigen/druck/id/86049/personen/3" />
		<!-- modifiziert="modifiziert" -->
	</rezept>
</rezepte>
