=== FunThomas424242/rezeptbuch/old-technology/rezepte.dtd
<?thomas-michel document-status="draft" version="1.0"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |rezepte.dtd       |         -  TODO description  | -->
<!--                                                     -->
<!-- datum            : | 07.09.2008|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->

<!ELEMENT rezepte (rezept)+>
<!ATTLIST rezepte titel CDATA #IMPLIED>

<!ELEMENT rezept  ( titel, untertitel?, datum, (ungetestet | test), verwertung?
				  , produkte?, zutaten, beilagen?, zubereitung, tipps?, quelle?)>

<!ELEMENT titel (#PCDATA)>
<!ELEMENT untertitel (#PCDATA)>
<!ELEMENT datum (#PCDATA)>
<!ELEMENT ungetestet EMPTY>
<!ELEMENT test (bemerkung)+>
<!ELEMENT bemerkung (#PCDATA)>

<!ELEMENT zutaten (zutat)+>

<!ELEMENT zutat EMPTY>
<!ATTLIST zutat name CDATA #REQUIRED>
<!ATTLIST zutat menge CDATA #REQUIRED>
<!ATTLIST zutat einheit CDATA #IMPLIED>
<!ATTLIST zutat code ID	#REQUIRED>

<!ELEMENT beilagen (beilage)+>
<!ELEMENT beilage (#PCDATA)>

<!ELEMENT verwertung (rest)+>
<!ELEMENT rest EMPTY>
<!ATTLIST rest name CDATA #REQUIRED>

<!ELEMENT zubereitung (aktion)+>
<!ELEMENT aktion (#PCDATA|zutatref)*>

<!ELEMENT zutatref (#PCDATA) >
<!ATTLIST zutatref code IDREF #REQUIRED>

<!ELEMENT produkte (produkt)+>

<!ELEMENT produkt EMPTY>
<!ATTLIST produkt beschreibung CDATA #REQUIRED>
<!ATTLIST produkt ean CDATA #IMPLIED>
<!ATTLIST produkt uba CDATA #IMPLIED>
<!ATTLIST produkt preis CDATA #IMPLIED>
<!ATTLIST produkt haendler CDATA #IMPLIED>
<!ATTLIST produkt hersteller CDATA #IMPLIED>

<!ELEMENT tipps (tipp)+>
<!ELEMENT tipp (#PCDATA)>

<!ELEMENT quelle EMPTY>
<!ATTLIST quelle name CDATA #REQUIRED>
<!ATTLIST quelle modifiziert CDATA #FIXED "modifiziert">

=== FunThomas424242/rezeptbuch/old-technology/NudelnMitTomatensosse.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |NudelnMitTomatensosse.xml|  -  TODO description  | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->
<!-- 
 standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
 :
 + Elementtypen, deren Inhalt weitere Elemente enthält, falls Leerraum (WhiteSpace)
   direkt innerhalb einer Instanz solcher Typen erscheint
 :
 -->
<rezepte>
	<rezept>
		<titel>Nudeln mit Tomatensosse</titel>
		<untertitel>Studenten Art</untertitel>
		<datum>22.09.2006</datum>
		<test>
			<bemerkung>
			Ausreichend für 2 Erwachsene und 3 Kinder.
			</bemerkung>
			<bemerkung>
			In der Regel bleibt ein Teil der Nudeln über.
			Diese können dann z.B. durch Braten verwertet werden.
			Dabei kann dann auch gleich die andere Hälfte vom Tomatenmark
			vernichtet werden.
			</bemerkung>
		</test>
		<produkte>
			<produkt beschreibung="1 Packung Preiswerte Spaghetti (500g)"
					 ean="8000255111997"
					 preis="0,87 €"
			         hersteller="Marktkauf Eigenmarke Gut und Billig"/>
			<produkt beschreibung="1 Büchse doppelt konzentriertes Tomatenmark (800g)"
					 ean="8005111200105"
					 preis="0,99 €"
					 hersteller="No Name"/>
			<produkt beschreibung="1 Fleischwurst (650g)"
					 ean="4002123111287"
					 hersteller="Marktkauf Eigenmarke Gut und Billig"/>
			<produkt beschreibung="1 Packung Speisesalz "/>
			<produkt beschreibung="1 Packung Spaghetti Gewürz"/>
			<produkt beschreibung="1 grosse Gemüsezwiebel"/>
			<produkt beschreibung="1 Tüte geriebenen Käse"
					 ean="4012965430514"
					 preis="0,99 €"
					 hersteller="Marktkauf Eigenmarke Gut und Billig"/>
		</produkte>
		<zutaten>
			<zutat name="Fleischwurst"
				   menge="325"
				   einheit="g"
				   code="fleischwurst"/> 
			<zutat name="Spaghetti"
				   menge="500" 
				   einheit="g"
				   code="nudeln"/>
			<zutat name="Gemüsezwiebel" 
					menge="1" 
					code="zwiebel"/>
			<zutat name="Tomatenmark" 
					menge="6" 
					einheit="reichlich gehäufte Esslöffel"
					code="tomatenmark"/>		
			<zutat name="Geriebener Käse" 
					menge="1"
					einheit="Tüte"
					code="reibekaese"/>	
			<zutat name="Salz" 
					menge="1"
					einheit="Priese"
					code="salz"/>		
			<zutat name="Spaghetti Gewürz" 
					menge="nach Bedarf" 
					code="wuerze"/>	
			<zutat name="Sonnenblumenöl"
				   menge="ca. 3"
				   einheit="Eßlöffel"
				   code="oel"/>															   
		</zutaten>
		<beilagen>
			<beilage>
			Als Nachtisch eignet sich jegliches Kompott.
			</beilage>
		</beilagen>
		<zubereitung>
			<aktion>
			Eine Pfanne mit ein wenig <zutatref code="oel" >Öl</zutatref>
			erhitzen (E-Herd Stufe III).
			</aktion>
			<aktion>
			In der Zwischenzeit die <zutatref code="fleischwurst">Fleischwurst
			</zutatref>in kleine Stifte oder Würfel schneiden. Und die 
			<zutatref code="zwiebel">Zwiebel</zutatref> in kleine Würfel 
			schneiden. 
			</aktion> 
			<aktion>
			Die Fleischwurst in die Pfanne geben und braten bis sie eine
			gold braune Färbung annimmt.
			</aktion>
			<aktion>
			Wenn die Wurst gold braun ist wird die gewürfelte Zwiebel zugegeben.
			</aktion>
			<aktion>
			Ist nun auch die Zwiebel noch gold braun, dann geben wir ca. 200 ml 
			Wasser zu und löschen die Mischung ab.
			</aktion>
			<aktion>
			Jetzt etwa 6 Eßlöffel Tomatenmark zugeben, alles schön verrühren,
			das restliche Wasser (ca. 400 ml) zugeben und kurz aufkochen lassen. 
			</aktion>
			<aktion>
			Dann auf Stufe 1 die Tomatensosse warm halten.
			</aktion>
			<aktion>
			Die Nudel zubereiten indem wir einen Topf 3/4 mit Wasser füllen,
			eine Prise Salz zugeben und die Nudel hineinlegen. E-Herd auf Stufe
			III.
			</aktion>
			<aktion>
			Die Nudeln auf Stufe II weiter kochen bis sie gar sind.
			Nudeln sind gar, wenn man eine Nudel herausnehmen, 
			sie gegen den Herd werfen kann und diese nicht dann nicht vom Herd
			abfällt.
			</aktion>
			<aktion>
			Nudeln abschrecken. Dazu wird der Topf vom Herd genommen und das
			Wasser abgegossen (dekantieren indem man den Deckel etwas verschiebt).
			Anschliessend Topf und Nudel mit kaltem Wasser auffüllen und wieder
			abgiessen. Vorgang solange wiederholen bis keine mehligfarbige Brühe 
			mehr abläuft - in der Regel sollte 1 mal reichen.
			</aktion>
			
		</zubereitung>
		<tipps>
			<tipp>
				Durch Zugabe von Instant Suppenpulver (Gemüsebrühe) erhalten die
				Nudeln beim Kochen einen würzigeren Geschmack und kleben 
				nach dem Abschrecken nicht so.
			</tipp>
			<tipp>
				Sollten die Nudel zu stark kleben, kann man nach dem Abschrecken
				etwas Butter hinzugeben. Dadurch wird das weitere Kleben 
				verhindert.
			</tipp>
			<tipp>
				Beim Abschrecken bitte gut mit kalten Wasser durchspülen - es 
				hilft nichts nur in den Topf zu schauen (egal wie sie aussehen
				;-))
			</tipp>
		</tipps>
		<quelle modifiziert="modifiziert" name="der Studenten WG"/>
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/KomarKekse.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
	<!-- $Id$ -->
	<!-- =================================================== -->
	<!-- |KomarKekse.xml|  -  TODO description  | -->
	<!--                                                     -->
	<!-- begin            : | 21.09.2006|                  | -->
	<!-- copyright        : | (C) 2006 by tmichel          | -->
	<!-- email            : |development@thomas-michel.info| -->
	<!-- =================================================== -->
	<!--
		******************************************************************************
		* * * This document is a free paper; you can redistribute it and/or
		modify * * it under the terms of the GNU Free Documentation License as
		published * * by the Free Software Foundation; either version 1.2 of
		the License, or * * (at your option) any later version. * * *
		******************************************************************************
	-->
	<!--
		standalone="no" gefordert nach XML in der Praxis S.400 (ISBN
		3-8273-1636-7) bei : + Elementtypen, deren Inhalt weitere Elemente
		enthält, falls Leerraum (WhiteSpace) direkt innerhalb einer Instanz
		solcher Typen erscheint :
	-->
<rezepte>
	<rezept>
		<titel>Komar-Kekse</titel>
		<datum>23.12.2008</datum>
		<test>
			<bemerkung>
				Relativ einfach, verdammt süß dafür aber weich
			</bemerkung>
		</test>
		<produkte>
			<produkt beschreibung="1 Packung Butter" haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung braunen Zucker" haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung Mehl z.B. Typ 405" haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="3 Eier" haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Röhrchen Vanillearoma" haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung gemahlenen Zimt" haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung Salz" haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung granulierten Zucker z.B. Hagelzucker"
				haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Glas Erdbeermarmelade" haendler="Marktkauf">
			</produkt>
		</produkte>
		<zutaten>
			<zutat name="Mehl" menge="250" einheit="g" code="mehl" />
			<zutat name="Butter" menge="125" einheit="g" code="butter" />
			<zutat name="braunen Zucker" menge="125" einheit="g" code="zucker" />
			<zutat name="Eier" menge="3" code="eier" />
			<zutat name="Vanillearoma" menge="1/2" einheit="TL" code="vanillearoma" />
			<zutat name="Salz" menge="1/4" einheit="TL" code="salz" />
			<zutat name="Zimt" menge="1" einheit="TL" code="zimt" />
			<zutat name="granulierten Zucker" menge="1" einheit="Suppentasse"
				code="hagelzucker" />
		</zutaten>
		<zubereitung>
			<aktion>Butter im Topf auf kleinster Stufe zergehen lassen und
				sofort wieder runter vom Herd.
			</aktion>
			<aktion>In die Butter den braunen Zucker eingeben und mittels
				Schneebesen schaumig schlagen.</aktion>
			<aktion>Zu dem Gemisch wird 1 Ei, das Mehl, die Vanille, der Zimt
				und das Salz dazugegeben.</aktion>
			<aktion>Alles schön verrühren - um so kälter es wird um so eher
				sieht es wie brauner Rührteig aus.</aktion>
			<aktion>Irgendwann sollte der Teig nicht mehr so kleben und
				sich eine Kugel formen lassen - ich habe hier mit Mehl nachgeholfen
				damit er nicht mehr so klebte.</aktion>
			<aktion>Ist es gelungen den Teig zu einer Kugel zu formen, dann
				kommt dieser 15 Minuten in den Kühlschrank.</aktion>
			<aktion>In der Zeit des Kühlens kann der Herd auf 200 Grad
				vorgeheizt werden.</aktion>
			<aktion>Das restliche Ei schaumig schlagen und den granulierten
				Zucker in eine Suppentasse oder einen Teller geben.</aktion>
			<aktion>Nachdem der Teig 15 Minuten gekühlt hat (er sollte
				jetzt nicht mehr kleben) Stückchen in Keksgröße entnehmen und als
				Ball rollen, im Ei und dann im Zucker wälzen und auf ein gefettetes
				Blech geben.</aktion>
			<aktion>Auf dem Blech den Ball so eindrücken, dass eine Kuhle
				entsteht. In diese wird die Marmelade gegeben.</aktion>
			<aktion>Die Kekse etwa 10 Minuten backen.</aktion>
		</zubereitung>
		<tipps>
			<tipp>Aus meiner Sicht kann es nicht schaden deutlich mehr Mehl zu
				nehmen oder weniger Butter, aber ich habe es noch nicht probiert wie
				sich das auswirkt. Ich würde erwarten, dass die Kekse härter werden
				und nicht mehr so süss sind.</tipp>
			<tipp>Die Glasur mit dem Ei, dem granulierten Zucker und der
				Marmelade würde ich weglassen. Stattdessen hilft vielleicht
				Kokosraspel
				aber ob das dann schmeckt muss man testen.</tipp>
			<tipp>Nach dem Backen die Kekse erst kühlen lassen, da sie noch
				nicht fest sind. Stabilität erlangen die Kekse erst beim Kühlen</tipp>
		</tipps>
		<quelle
			name="dem offiziellen Star Trek Kochbuch, ISBN: 3-89365-796-7, S. 269-270" />
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/Schokoglasur.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |Schokoglasur.xml|  -  TODO description  | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->
<!-- 
 standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
 :
 + Elementtypen, deren Inhalt weitere Elemente enthält, falls Leerraum (WhiteSpace)
   direkt innerhalb einer Instanz solcher Typen erscheint
 :
 -->
<rezepte>
	<rezept>
		<titel>Schokoglasur</titel>
		<datum>16.06.2007</datum>
		<test>
			<bemerkung>
			Geht schnell - ist aber sehr süss.
			</bemerkung>
		</test>
		<produkte>
			<produkt beschreibung="1 Packung Puderzucker"
					 haendler="Marktkauf">
			</produkt>
			<produkt beschreibung="1 Packung Kakao"
					 haendler="Marktkauf">
			</produkt>
		</produkte>
		<zutaten>
			<zutat name="Puderzucker"
				   menge="150"
				   einheit="g"
				   code="zucker"/> 
			<zutat name="Kakao"
				   menge="2" 
				   einheit="gehäufte EL"
				   code="kakao"/>
			<zutat name="Wasser" 
					menge="2-3" 
					einheit="EL"
					code="wasser"/>
		</zutaten>
		<zubereitung>
			<aktion>Puderzucker und Kakao mischen
:			</aktion>		
			<aktion>Die Mischung mit heissem Wasser glatt rühren</aktion>
			<aktion>Mit einem Messer die Glasur auf dem Kuchen verteilen</aktion>
		</zubereitung>
		<quelle name="Packung für Gloria Schoko Kuchen"/>
	</rezept>
</rezepte>

=== FunThomas424242/rezeptbuch/old-technology/Schmorgurken.xml
<?thomas-michel document-status="draft" version="1.2"?>
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE rezept SYSTEM "../../rezepte.dtd">
<?xml-stylesheet href="../../style.xsl" type="text/xsl"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!-- $Id$ -->
<!-- =================================================== -->
<!-- |NudelnMitTomatensosse.xml|  -  TODO description  | -->
<!--                                                     -->
<!-- begin            : | 21.09.2006|                  | -->
<!-- copyright        : | (C) 2006 by tmichel          | -->
<!-- email            : |development@thomas-michel.info| -->
<!-- =================================================== -->
<!--
 ******************************************************************************
 *                                                                            *
 *   This document is a free paper; you can redistribute it and/or modify     *
 *   it under the terms of the GNU Free Documentation License as published    *
 *   by the Free Software Foundation; either version 1.2 of the License, or   *
 *   (at your option) any later version.                                      *
 *                                                                            *
 ******************************************************************************
 -->
<!-- 
 standalone="no" gefordert nach XML in der Praxis S.400 (ISBN 3-8273-1636-7) bei
 :
 + Elementtypen, deren Inhalt weitere Elemente enthält, falls Leerraum (WhiteSpace)
   direkt innerhalb einer Instanz solcher Typen erscheint
 :
 -->
<rezepte>
	<rezept>
		<titel>Schorgurken</titel>
		<datum>04.01.2007</datum>
		<ungetestet/>
		<zutaten>
			<zutat name="Gurken"
				   menge="2"
				   einheit="Stück"
				   code="gurke"/> 
			<zutat name="Tomaten"
				   menge="8" 
				   einheit="Stück"
				   code="tomate"/>
			<zutat name="Kartoffeln" 
					menge="20" 
					einheit="Stück"
					code="kartoffel"/>
			<zutat name="Gemüsezwiebel" 
					menge="1" 
					code="zwiebel"/>		
			<zutat name="Öl" 
					menge="1"
					einheit="Schuss"
					code="oel"/>	
			<zutat name="Thymian" 
					menge="1"
					einheit="Priese"
					code="thymian"/>		
			<zutat name="Buletten" 
					menge="5" 
					einheit="Stück"
					code="buletten"/>	
		</zutaten>
		<zubereitung>
			<aktion>
:			</aktion>		
		</zubereitung>
		<!-- quelle modifiziert="modifiziert" name="der Studenten WG"/-->
	</rezept>
</rezepte>
